"""add sentiment_fusion table

Revision ID: 0b33a634d5a8
Revises: 554913952376
Create Date: 2025-10-11 09:32:05.148514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b33a634d5a8'
down_revision: Union[str, Sequence[str], None] = '554913952376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_fusion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('avg_news_sentiment', sa.Float(), nullable=True),
    sa.Column('whale_emotion', sa.Float(), nullable=True),
    sa.Column('fear_greed_index', sa.Float(), nullable=True),
    sa.Column('social_score', sa.Float(), nullable=True),
    sa.Column('final_sentiment', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_fusion_symbol'), 'sentiment_fusion', ['symbol'], unique=False)
    op.create_index('ix_sentiment_fusion_symbol_ts', 'sentiment_fusion', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_sentiment_fusion_timestamp'), 'sentiment_fusion', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_fusion_timestamp'), table_name='sentiment_fusion')
    op.drop_index('ix_sentiment_fusion_symbol_ts', table_name='sentiment_fusion')
    op.drop_index(op.f('ix_sentiment_fusion_symbol'), table_name='sentiment_fusion')
    op.drop_table('sentiment_fusion')
    # ### end Alembic commands ###
