"""Add developer_activity table

Revision ID: 4c208aac05da
Revises: ad249ab5c0a6
Create Date: 2025-10-11 08:14:31.033813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c208aac05da'
down_revision: Union[str, Sequence[str], None] = 'ad249ab5c0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('open_issues', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developer_activity_id'), 'developer_activity', ['id'], unique=False)
    op.create_index(op.f('ix_developer_activity_symbol'), 'developer_activity', ['symbol'], unique=False)
    op.create_index(op.f('ix_developer_activity_timestamp'), 'developer_activity', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_developer_activity_timestamp'), table_name='developer_activity')
    op.drop_index(op.f('ix_developer_activity_symbol'), table_name='developer_activity')
    op.drop_index(op.f('ix_developer_activity_id'), table_name='developer_activity')
    op.drop_table('developer_activity')
    # ### end Alembic commands ###
