"""initial tables

Revision ID: 6caad0e296d3
Revises: b3361462dade
Create Date: 2025-10-25 17:31:36.459698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6caad0e296d3'
down_revision: Union[str, Sequence[str], None] = 'b3361462dade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options_chain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('mark_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Float(), nullable=True),
    sa.Column('iv', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'expiry', 'strike', 'option_type', 'timestamp', name='uq_optchain_sym_ex_str_ot_ts')
    )
    op.create_index('ix_optchain_contract', 'options_chain', ['symbol', 'expiry', 'strike', 'option_type'], unique=False)
    op.create_index('ix_optchain_sym_ts', 'options_chain', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_options_chain_expiry'), 'options_chain', ['expiry'], unique=False)
    op.create_index(op.f('ix_options_chain_id'), 'options_chain', ['id'], unique=False)
    op.create_index(op.f('ix_options_chain_option_type'), 'options_chain', ['option_type'], unique=False)
    op.create_index(op.f('ix_options_chain_strike'), 'options_chain', ['strike'], unique=False)
    op.create_index(op.f('ix_options_chain_symbol'), 'options_chain', ['symbol'], unique=False)
    op.create_index(op.f('ix_options_chain_timestamp'), 'options_chain', ['timestamp'], unique=False)
    op.create_table('options_derived_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_put_volume', sa.Float(), nullable=True),
    sa.Column('total_call_volume', sa.Float(), nullable=True),
    sa.Column('put_call_volume_ratio', sa.Float(), nullable=True),
    sa.Column('total_put_oi', sa.Float(), nullable=True),
    sa.Column('total_call_oi', sa.Float(), nullable=True),
    sa.Column('put_call_oi_ratio', sa.Float(), nullable=True),
    sa.Column('avg_iv_near_term', sa.Float(), nullable=True),
    sa.Column('avg_iv_mid_term', sa.Float(), nullable=True),
    sa.Column('iv_skew_25d', sa.Float(), nullable=True),
    sa.Column('iv_atm_near', sa.Float(), nullable=True),
    sa.Column('iv_atm_mid', sa.Float(), nullable=True),
    sa.Column('iv_atm_far', sa.Float(), nullable=True),
    sa.Column('iv_term_slope_near_mid', sa.Float(), nullable=True),
    sa.Column('iv_term_slope_near_far', sa.Float(), nullable=True),
    sa.Column('iv_term_slope_reg_logT', sa.Float(), nullable=True),
    sa.Column('smile_25d_put_iv', sa.Float(), nullable=True),
    sa.Column('smile_atm_iv', sa.Float(), nullable=True),
    sa.Column('smile_25d_call_iv', sa.Float(), nullable=True),
    sa.Column('smile_curvature', sa.Float(), nullable=True),
    sa.Column('gex_total', sa.Float(), nullable=True),
    sa.Column('gex_calls', sa.Float(), nullable=True),
    sa.Column('gex_puts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', name='_symbol_timestamp_uc_options_derived')
    )
    op.create_index(op.f('ix_options_derived_metrics_id'), 'options_derived_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_options_derived_metrics_symbol'), 'options_derived_metrics', ['symbol'], unique=False)
    op.create_index(op.f('ix_options_derived_metrics_timestamp'), 'options_derived_metrics', ['timestamp'], unique=False)
    op.create_table('risk_learned_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('sl_atr_mult', sa.Float(), nullable=False),
    sa.Column('tp_atr_mult', sa.Float(), nullable=False),
    sa.Column('trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('gross_pnl', sa.Float(), nullable=False),
    sa.Column('gross_pnl_after_fees', sa.Float(), nullable=False),
    sa.Column('avg_win', sa.Float(), nullable=False),
    sa.Column('avg_loss', sa.Float(), nullable=False),
    sa.Column('trading_day', sa.String(), nullable=False),
    sa.Column('day_pnl', sa.Float(), nullable=False),
    sa.Column('rolling_equity_peak', sa.Float(), nullable=False),
    sa.Column('rolling_equity_min', sa.Float(), nullable=False),
    sa.Column('last_regime', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_learned_state_symbol'), 'risk_learned_state', ['symbol'], unique=True)
    op.create_table('risk_settings_global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_equity_usd', sa.Float(), nullable=False),
    sa.Column('max_portfolio_leverage', sa.Float(), nullable=False),
    sa.Column('max_concurrent_positions', sa.Integer(), nullable=False),
    sa.Column('target_daily_vol', sa.Float(), nullable=False),
    sa.Column('min_position_usd', sa.Float(), nullable=False),
    sa.Column('atr_length', sa.Integer(), nullable=False),
    sa.Column('sl_atr_mult_init', sa.Float(), nullable=False),
    sa.Column('tp_atr_mult_init', sa.Float(), nullable=False),
    sa.Column('base_confidence_cutoff', sa.Float(), nullable=False),
    sa.Column('max_confidence_boost', sa.Float(), nullable=False),
    sa.Column('regime_risk_multipliers', sa.JSON(), nullable=False),
    sa.Column('daily_loss_limit_pct', sa.Float(), nullable=False),
    sa.Column('rolling_max_dd_pct', sa.Float(), nullable=False),
    sa.Column('per_trade_risk_pct_cap', sa.Float(), nullable=False),
    sa.Column('ewma_alpha', sa.Float(), nullable=False),
    sa.Column('min_trades_to_learn', sa.Integer(), nullable=False),
    sa.Column('bandit_lr', sa.Float(), nullable=False),
    sa.Column('min_tp_sl_ratio', sa.Float(), nullable=False),
    sa.Column('min_sl_atr_mult', sa.Float(), nullable=False),
    sa.Column('max_sl_atr_mult', sa.Float(), nullable=False),
    sa.Column('min_tp_atr_mult', sa.Float(), nullable=False),
    sa.Column('max_tp_atr_mult', sa.Float(), nullable=False),
    sa.Column('taker_fee_bps', sa.Float(), nullable=False),
    sa.Column('default_adapter', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_settings_symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('max_symbol_leverage', sa.Float(), nullable=True),
    sa.Column('max_symbol_exposure_pct', sa.Float(), nullable=True),
    sa.Column('atr_length', sa.Integer(), nullable=True),
    sa.Column('sl_atr_mult_init', sa.Float(), nullable=True),
    sa.Column('tp_atr_mult_init', sa.Float(), nullable=True),
    sa.Column('base_confidence_cutoff', sa.Float(), nullable=True),
    sa.Column('regime_risk_multipliers', sa.JSON(), nullable=True),
    sa.Column('min_position_usd', sa.Float(), nullable=True),
    sa.Column('per_trade_risk_pct_cap', sa.Float(), nullable=True),
    sa.Column('taker_fee_bps', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_settings_symbol_symbol'), 'risk_settings_symbol', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_settings_symbol_symbol'), table_name='risk_settings_symbol')
    op.drop_table('risk_settings_symbol')
    op.drop_table('risk_settings_global')
    op.drop_index(op.f('ix_risk_learned_state_symbol'), table_name='risk_learned_state')
    op.drop_table('risk_learned_state')
    op.drop_index(op.f('ix_options_derived_metrics_timestamp'), table_name='options_derived_metrics')
    op.drop_index(op.f('ix_options_derived_metrics_symbol'), table_name='options_derived_metrics')
    op.drop_index(op.f('ix_options_derived_metrics_id'), table_name='options_derived_metrics')
    op.drop_table('options_derived_metrics')
    op.drop_index(op.f('ix_options_chain_timestamp'), table_name='options_chain')
    op.drop_index(op.f('ix_options_chain_symbol'), table_name='options_chain')
    op.drop_index(op.f('ix_options_chain_strike'), table_name='options_chain')
    op.drop_index(op.f('ix_options_chain_option_type'), table_name='options_chain')
    op.drop_index(op.f('ix_options_chain_id'), table_name='options_chain')
    op.drop_index(op.f('ix_options_chain_expiry'), table_name='options_chain')
    op.drop_index('ix_optchain_sym_ts', table_name='options_chain')
    op.drop_index('ix_optchain_contract', table_name='options_chain')
    op.drop_table('options_chain')
    # ### end Alembic commands ###
