"""Add onchain_metrics table

Revision ID: ad249ab5c0a6
Revises: 7a3170b624ac
Create Date: 2025-10-11 07:12:01.645659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad249ab5c0a6'
down_revision: Union[str, Sequence[str], None] = '7a3170b624ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onchain_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('whale_tx_count', sa.Integer(), nullable=True),
    sa.Column('whale_volume_usd', sa.Float(), nullable=True),
    sa.Column('exchange_net_flow_usd', sa.Float(), nullable=True),
    sa.Column('active_addresses', sa.Integer(), nullable=True),
    sa.Column('total_tx', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onchain_metrics_id'), 'onchain_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_onchain_metrics_symbol'), 'onchain_metrics', ['symbol'], unique=False)
    op.create_index(op.f('ix_onchain_metrics_timestamp'), 'onchain_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onchain_metrics_timestamp'), table_name='onchain_metrics')
    op.drop_index(op.f('ix_onchain_metrics_symbol'), table_name='onchain_metrics')
    op.drop_index(op.f('ix_onchain_metrics_id'), table_name='onchain_metrics')
    op.drop_table('onchain_metrics')
    # ### end Alembic commands ###
