"""Add OHLC columns and unique indexes

Revision ID: b3361462dade
Revises: 0b33a634d5a8
Create Date: 2025-10-13 14:23:40.756568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3361462dade'
down_revision: Union[str, Sequence[str], None] = '0b33a634d5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('futures_market_data', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_futures_market_data_timestamp'), 'futures_market_data', ['timestamp'], unique=False)
    op.create_index('ix_futures_symbol_timestamp', 'futures_market_data', ['symbol', 'timestamp'], unique=True)
    op.add_column('market_data', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('market_data', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('market_data', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('market_data', sa.Column('close', sa.Float(), nullable=True))
    op.alter_column('market_data', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    op.create_index('ix_market_symbol_timestamp', 'market_data', ['symbol', 'timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_symbol_timestamp', table_name='market_data')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.alter_column('market_data', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('market_data', 'close')
    op.drop_column('market_data', 'low')
    op.drop_column('market_data', 'high')
    op.drop_column('market_data', 'open')
    op.drop_index('ix_futures_symbol_timestamp', table_name='futures_market_data')
    op.drop_index(op.f('ix_futures_market_data_timestamp'), table_name='futures_market_data')
    op.alter_column('futures_market_data', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
