"""add orderbook and cross asset corr tables

Revision ID: 554913952376
Revises: 4c208aac05da
Create Date: 2025-10-11 09:27:10.702006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554913952376'
down_revision: Union[str, Sequence[str], None] = '4c208aac05da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cross_asset_corr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_symbol', sa.String(length=16), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('corr_btc_eth', sa.Float(), nullable=False),
    sa.Column('corr_btc_dxy', sa.Float(), nullable=False),
    sa.Column('corr_btc_ndx', sa.Float(), nullable=False),
    sa.Column('corr_btc_gold', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cac_ts_sym_win', 'cross_asset_corr', ['timestamp', 'base_symbol', 'window_minutes'], unique=False)
    op.create_index(op.f('ix_cross_asset_corr_base_symbol'), 'cross_asset_corr', ['base_symbol'], unique=False)
    op.create_index(op.f('ix_cross_asset_corr_timestamp'), 'cross_asset_corr', ['timestamp'], unique=False)
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('bid_volume', sa.Float(), nullable=False),
    sa.Column('ask_volume', sa.Float(), nullable=False),
    sa.Column('mid_price', sa.Float(), nullable=False),
    sa.Column('bid_ask_imb', sa.Float(), nullable=False),
    sa.Column('vw_price_skew', sa.Float(), nullable=False),
    sa.Column('cdv_1m', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_obs_ts_sym', 'orderbook_snapshots', ['timestamp', 'symbol'], unique=False)
    op.create_index(op.f('ix_orderbook_snapshots_symbol'), 'orderbook_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_orderbook_snapshots_timestamp'), 'orderbook_snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderbook_snapshots_timestamp'), table_name='orderbook_snapshots')
    op.drop_index(op.f('ix_orderbook_snapshots_symbol'), table_name='orderbook_snapshots')
    op.drop_index('ix_obs_ts_sym', table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    op.drop_index(op.f('ix_cross_asset_corr_timestamp'), table_name='cross_asset_corr')
    op.drop_index(op.f('ix_cross_asset_corr_base_symbol'), table_name='cross_asset_corr')
    op.drop_index('ix_cac_ts_sym_win', table_name='cross_asset_corr')
    op.drop_table('cross_asset_corr')
    # ### end Alembic commands ###
