"""Add F&G and Macro data tables

Revision ID: 7a3170b624ac
Revises: 91b9dedf14c3
Create Date: 2025-10-11 06:50:33.524398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3170b624ac'
down_revision: Union[str, Sequence[str], None] = '91b9dedf14c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fear_and_greed_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('value_classification', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fear_and_greed_index_id'), 'fear_and_greed_index', ['id'], unique=False)
    op.create_index(op.f('ix_fear_and_greed_index_timestamp'), 'fear_and_greed_index', ['timestamp'], unique=False)
    op.create_table('macro_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_data_id'), 'macro_data', ['id'], unique=False)
    op.create_index(op.f('ix_macro_data_indicator'), 'macro_data', ['indicator'], unique=False)
    op.create_index(op.f('ix_macro_data_timestamp'), 'macro_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_macro_data_timestamp'), table_name='macro_data')
    op.drop_index(op.f('ix_macro_data_indicator'), table_name='macro_data')
    op.drop_index(op.f('ix_macro_data_id'), table_name='macro_data')
    op.drop_table('macro_data')
    op.drop_index(op.f('ix_fear_and_greed_index_timestamp'), table_name='fear_and_greed_index')
    op.drop_index(op.f('ix_fear_and_greed_index_id'), table_name='fear_and_greed_index')
    op.drop_table('fear_and_greed_index')
    # ### end Alembic commands ###
