"""Add funding_rates table

Revision ID: 91b9dedf14c3
Revises: a6cbef7c761a
Create Date: 2025-10-11 06:39:42.943018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b9dedf14c3'
down_revision: Union[str, Sequence[str], None] = 'a6cbef7c761a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('funding_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_rates_id'), 'funding_rates', ['id'], unique=False)
    op.create_index(op.f('ix_funding_rates_symbol'), 'funding_rates', ['symbol'], unique=False)
    op.create_index(op.f('ix_funding_rates_timestamp'), 'funding_rates', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funding_rates_timestamp'), table_name='funding_rates')
    op.drop_index(op.f('ix_funding_rates_symbol'), table_name='funding_rates')
    op.drop_index(op.f('ix_funding_rates_id'), table_name='funding_rates')
    op.drop_table('funding_rates')
    # ### end Alembic commands ###
